using System.Numerics;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Linq;
using Content.Client.Administration.UI.CustomControls;
using Robust.Client.Console;
using Robust.Client.Graphics;

namespace Content.Client._Wormix.Administration.CharacterWhitelist.UI.Character;

[GenerateTypedNameReferences]
public sealed partial class CharacterWhitelistWindow : DefaultWindow
{
    private readonly List<(OptionButton, IPrototype)> _roleDropdown = new();

    [Dependency] private readonly IEntityManager _entMan = default!;
    [Dependency] private readonly IPrototypeManager _protoMan = default!;
    [Dependency] private readonly IClientConsoleHost _console = default!;

    private int _characterId;
    private const string ExpandedArrow = "▼";
    private const string ContractedArrow = "▶";

    public CharacterWhitelistWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var departmentJobs = _protoMan.EnumeratePrototypes<DepartmentPrototype>()
            .OrderBy(x => x.Weight);
        foreach (var proto in departmentJobs)
        {
            var roles = proto.Roles.Select(x => _protoMan.Index(x))
                .OrderBy(x => x.ID);

            CreateRoleGroup(proto.ID, proto.Color, roles);
        }
    }

    public void SetWhitelists(List<(string, bool)> whitelists)
    {
        foreach (var roleRestriction in whitelists)
        {
            var roleDropdown = _roleDropdown
                .Find(x => x.Item2.ID == roleRestriction.Item1);

            if (roleRestriction.Item2)
                roleDropdown.Item1.SelectId(1);
            else
                roleDropdown.Item1.SelectId(2);
        }

    }

    public void SetCharacter(int? id, string characterName)
    {
        if (id == null)
        {
            Title = "Ошибка";
            return;
        }

        Title = Loc.GetString("ban-list-title", ("player", characterName));
        _characterId = (int)id;
    }


    private void CreateRoleGroup<T>(string groupName, Color color, IEnumerable<T> roles) where T : class, IPrototype
    {
        var outerContainer = new BoxContainer
        {
            Name = $"{groupName}GroupOuterBox",
            HorizontalExpand = true,
            VerticalExpand = true,
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(4),
        };

        // Stores stuff like ban all and expand buttons.
        var roleGroupHeader = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
        };

        // Stores the role checkboxes themselves.
        var innerContainer = new GridContainer
        {
            Name = $"{groupName}GroupInnerBox",
            HorizontalExpand = true,
            Columns = 2,
            Visible = false,
            Margin = new Thickness(15, 5, 0, 5),
        };

        CreateRoleGroupHeader(groupName, roleGroupHeader, color, innerContainer);

        outerContainer.AddChild(roleGroupHeader);

        // Add the roles themselves
        foreach (var role in roles)
        {
            AddRoleDropDown(groupName, role.ID, innerContainer);
        }

        outerContainer.AddChild(innerContainer);

        RolesList.AddChild(new PanelContainer
        {
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = color
            }
        });
        RolesList.AddChild(outerContainer);
        RolesList.AddChild(new HSeparator());
    }

    private void CreateRoleGroupHeader(string groupName, BoxContainer header, Color color, GridContainer innerContainer)
    {
        var hideButton = new Button
        {
            Text = Loc.GetString("role-bans-expand-roles") + " " + ContractedArrow,
            ToggleMode = true,
        };
        hideButton.OnPressed += args =>
        {
            innerContainer.Visible = args.Button.Pressed;
            ((Button)args.Button).Text = args.Button.Pressed
                ? Loc.GetString("role-bans-contract-roles") + " " + ExpandedArrow
                : Loc.GetString("role-bans-expand-roles") + " " + ContractedArrow;
        };
        header.AddChild(new Label
        {
            Text = groupName,
            Modulate = color,
            Margin = new Thickness(0, 0, 5, 0),
        });

        header.AddChild(hideButton);
    }


    private void AddRoleDropDown(string group, string role, GridContainer roleGroupInnerContainer)
    {
        var roleCheckboxContainer = new BoxContainer()
        {
            HorizontalExpand = true
        };
        var titleJobName = new Label()
        {
            Text =  role,
            HorizontalAlignment = HAlignment.Left,
            HorizontalExpand = true,
        };
        var dropDown = new OptionButton()
        {
            HorizontalAlignment = HAlignment.Right,
            HorizontalExpand = true,
        };

        dropDown.OnItemSelected += args =>
        {
            args.Button.SelectId(args.Id);

            if(args.Id == 0)
                _console.ExecuteCommand($"remcharacterjobwhitelist {_characterId} {role}");
            else if (args.Id == 1)
            {
                _console.ExecuteCommand($"addcharacterjobwhitelist {_characterId} {role} true");
            }
            else if (args.Id == 2)
            {
                _console.ExecuteCommand($"addcharacterjobwhitelist {_characterId} {role} false");
            }

        };



        dropDown.AddItem("отсутствует");
        dropDown.AddItem("запрет");
        dropDown.AddItem("разрешение");


        IPrototype rolePrototype;

        if (_protoMan.TryIndex<JobPrototype>(role, out var jobPrototype))
            rolePrototype = jobPrototype;
        else
        {
            return;
        }

        if (jobPrototype is not null && _protoMan.TryIndex(jobPrototype.Icon, out var iconProto))
        {
            var jobIconTexture = new TextureRect
            {
                Texture = _entMan.System<SpriteSystem>().Frame0(iconProto.Icon),
                TextureScale = new Vector2(2.5f, 2.5f),
                Stretch = TextureRect.StretchMode.KeepCentered,
                Margin = new Thickness(5, 0, 0, 0),
            };
            roleCheckboxContainer.AddChild(jobIconTexture);
        }

        roleCheckboxContainer.AddChild(titleJobName);
        roleCheckboxContainer.AddChild(dropDown);


        roleGroupInnerContainer.AddChild(roleCheckboxContainer);

        _roleDropdown.Add((dropDown, rolePrototype));
    }


}
