using Content.Shared._Wormix;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Wormix.Administration.CharacterWhitelist.UI;

[GenerateTypedNameReferences]
public sealed partial class PlayerCharacterLine : BoxContainer, ICharacterListLine<SharedCharacter>
{
    public SharedCharacter Character { get; }

    public PlayerCharacterLine(SharedCharacter character)
    {
        RobustXamlLoader.Load(this);

        Character = character;

        PlayerCharacterListEui.SetData(this, character);
    }

}

