using Content.Client.Administration.UI.CustomControls;
using Content.Shared._Wormix;
using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Wormix.Administration.CharacterWhitelist.UI;

[GenerateTypedNameReferences]
public sealed partial class PlayersCharactersListWindow : DefaultWindow
{
    [Dependency] private readonly IClientConsoleHost _console = default!;

    public PlayersCharactersListWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void SetTitlePlayer(string playerName)
    {
        Title = Loc.GetString("ban-list-title", ("player", playerName));
    }

    public void SetCharacters(List<SharedCharacter> playerCharacters)
    {
        for (var i = CharactersList.ChildCount - 1; i >= 1; i--)
        {
            CharactersList.GetChild(i).Dispose();
        }

        foreach (var character in playerCharacters)
        {
            CharactersList.AddChild(new HSeparator());

            var line = new PlayerCharacterLine(character);

            CharactersList.AddChild(line);

            line.CharButton.OnPressed += _ =>
            {
                _console.ExecuteCommand($"characterwhitelistpanel {character.Id}");
            };
        }
    }
}

