- type: entity
  id: BaseStationGoal
  abstract: true
  components:
    - type: DepartmentGoal
      goals:
      #SEC
      - secInstruction
      - secContraband
      #MED
      - virusCheck
      - immuneCreate
      #SERVICE
      - dinnerDay
      - teaDay